apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: prometheus
      version: '25.11.1'
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 5m
  releaseName: prometheus
  values:
    path: ../../../../prometheus/values.yaml