apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: treafik
  chart:
    repository: https://traefik.github.io/charts
    name: traefik
    version: "26.0.0"
  # values:
  #   path: ../../../../traefik/values.yaml