apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: treafik
spec:
  releaseName: traefik
  chart:
    repository: "https://helm.traefik.io/traefik"
    name: traefik
    version: 26.0.0
  values:
    path: ../../../../traefik/values.yaml
    # additionalArguments:
    #   - "--api.insecure=true"
    # service:
    #   type: LoadBalancer