apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: traefik
      version: '26.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 5m
  releaseName: traefik
  values:
    path: ../../../../traefik/values.yaml