apiVersion: v1
kind: Service
metadata:
  name: brodin-webserver-service
  namespace: default
spec:
  selector:
    app: brodin-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80