apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft-server
    type: server
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - image: itzg/minecraft-server
        name: minecraft-server
