apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: glasscraft
      type: minecraft-server
  template:
    metadata:
      labels:
        name: glasscraft
        type: minecraft-server
    spec:
      containers:
        - name: minecraft-server-container
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565